# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-10 09:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, null=True)),
                ('type', models.CharField(blank=True, choices=[('A', 'Album'), ('S', 'Single')], max_length=1, null=True, verbose_name='Album or single?')),
                ('date', models.DateTimeField(null=True)),
                ('cover', models.ImageField(blank=True, null=True, upload_to='static/covers/', verbose_name='Cover image')),
                ('itunes', models.URLField(blank=True, null=True)),
                ('google_play', models.URLField(blank=True, null=True)),
                ('spotify', models.URLField(blank=True, null=True)),
                ('amazon', models.URLField(blank=True, null=True)),
                ('rdio', models.URLField(blank=True, null=True)),
                ('deezer', models.URLField(blank=True, null=True)),
                ('tidal', models.URLField(blank=True, null=True)),
                ('youtube', models.URLField(blank=True, null=True)),
                ('microsoft_groove', models.URLField(blank=True, null=True)),
                ('medianet', models.URLField(blank=True, null=True)),
                ('shazam', models.URLField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
