# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-10 09:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_auto_20160510_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='release',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='Cover image'),
        ),
    ]
