# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-10 09:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_auto_20160510_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='release',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='covers/', verbose_name='Cover image'),
        ),
    ]
