# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-10 10:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0004_auto_20160510_0936'),
    ]

    operations = [
        migrations.AddField(
            model_name='release',
            name='apple_music',
            field=models.URLField(blank=True, null=True),
        ),
    ]
