# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-11 02:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0005_release_apple_music'),
    ]

    operations = [
        migrations.AddField(
            model_name='release',
            name='sound_cloud',
            field=models.URLField(blank=True, null=True),
        ),
    ]
