# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-11 12:43
from __future__ import unicode_literals

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0006_release_sound_cloud'),
    ]

    operations = [
        migrations.AlterField(
            model_name='release',
            name='cover',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Cover image'),
        ),
    ]
